site_name: 久违的事演出曲目
site_url: https://stubbornleaf.github.io/jiuweideshi-songbook/
theme:
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details

nav:
  - 首页: index.md
  - 曲目:
      - 01 久违的事: songs/01-久违的事.md
      - 02 米店 : songs/米店.md
      - 03 安和桥 : songs/安和桥.md
      - 04 郭源潮 : songs/郭源潮.md
      - 05 在劫难逃 : songs/在劫难逃.md
      - 06 恋恋风尘 : songs/恋恋风尘.md
      - 07 想把我唱给你听 : songs/想把我唱给你听.md
      - 08 莉莉安 : songs/莉莉安.md
      - 09 夏日限定 : songs/夏日限定.md
      - 10 春风十里 : songs/春风十里.md
      - 11 我从这里走过 : songs/我从这里走过.md
      - 12 山阴路的夏天 : songs/山阴路的夏天.md
      - 13 模范情书 : songs/模范情书.md
      - 14 路过人间 : songs/路过人间.md
      - 15 One More Cup of Coffee : songs/One%20More%20Cup%20of%20Coffee.md
      - 16 乌云典当记 : 乌云典当记.md


extra_css:
  - stylesheets/extra.css
